name: NDK build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          submodules: true
          lfs: true
      - name: Install Powershell
        run: sudo apt-get install -y powershell

      #       - name: Cache Android NDK
      #         id: cache-ndk
      #         uses: actions/cache@v2
      #         env:
      #           cache-name: cache-ndk
      #           ndkname: android-ndk-r22
      #         with:
      #           path: ndk
      #           key: ${{ runner.os }}-${{ env.cache-name }}-${{ env.ndkname }}
      #           restore-keys: |
      #             ${{ runner.os }}-${{ env.cache-name }}-${{ env.ndkname }}

      - name: Setup NDK
        if: steps.cache-ndk.outputs.cache-hit != 'true'
        id: setup-ndk
        uses: nttld/setup-ndk@v1.0.3
        with:
          ndk-version: r22

      - name: Create ndkpath.txt
        run: echo ${{ steps.setup-ndk.outputs.ndk-path }} > ${GITHUB_WORKSPACE}/ndkpath.txt

      #       - name: Cache QPM
      #         id: cache-qpm
      #         uses: actions/cache@v2
      #         env:
      #           cache-name: cache-qpm
      #         with:
      #           path: QPM/QPM_Temp
      #           key: ${{ runner.os }}-qpm-${{ hashFiles('**/qpm.shared.json') }}
      #           restore-keys: |
      #             ${{ runner.os }}-qpm-

      - name: Get QPM
        if: steps.cache-qpm.outputs.cache-hit != 'true'
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yml
          name: QPM-ubuntu-x64
          path: QPM
          repo: sc2ad/QuestPackageManager

      - name: QPM Make shared file
        run: |
          chmod +x ./QPM/QPM
          ./QPM/QPM collect

      - name: QPM Dependencies Cache
        id: cache-qpm-deps
        uses: actions/cache@v2
        env:
          cache-name: cache-qpm-deps
        with:
          path: QPM_Temp
          key: cache-qpm-deps
          restore-keys: cache-qpm-deps

      - name: QPM Restore
        run: |
          chmod +x ./QPM/QPM
          ./QPM/QPM restore
      - name: Build
        run: |
          cd ${GITHUB_WORKSPACE}
          pwsh -Command ./build.ps1